create database relacao_global_moedas;
use relacao_global_moedas;
create table relacao_global_moedas(
PAÍS varchar(30) not null,
MOEDA varchar(30) not null,
CÓDIGO_MOEDA varchar(10) not null,
NÚMERO_CÓDIGO_MOEDA int not null
)  default charset = utf8mb4 ;

select * from relacao_global_moedas;
desc relacao_global_moedas;

insert into relacao_global_moedas values
/*PAÍS, MOEDA, CÓDIGO_MOEDA, NÚMERO_CÓDIGO_MOEDA */
("Afeganistão", "Afghani","AFN", "971"),
("Albania", "Lek","ALL", "971"),
('Alemanha', 'Euro', 'EUR', '978'),
('Andorra', 'Euro', 'EUR', '978'),
('Angola', 'Kwanza', 'AOA',	'973'),
('Anguila', 'Dólar do Caribe Oriental',	'XCD', '951'),
('Antártica', 'Nenhuma moeda universal', '', ''),		
('Antígua e Barbuda', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Argentina', 'Peso argentino', 'ARS', '032'),
('Argélia', 'Dinar argelino', 'DZD', '012'),
('Armênia', 'Dram armênio',	'AMD',	'051'),
('Aruba', 'Florim de Aruba', 'AWG', '533'),
('Arábia Saudita', 'Rial saudita', 'SAR', '682'),
('Austrália', 'Dólar australiano', 'AUD', '036'),
('Azerbaijão', 'Manat do Azerbaijão', 'AZN', '944'),
('Bahamas', 'Dólar das Bahamas', 'BSD', '044'),
('Bahrein', 'Dinar do Bahrein', 'BHD', '048'),
('Bangladesh', 'Taka', 'BDT', '050'),
('Barbados', 'Dólar de Barbados', 'BBD', '052'),
('Belarus', 'Rublo bielorrusso', 'BYR', '974'),
('Belize', 'Dólar de Belize', 'BZD', '084'),
('Benin', 'CFA Franco BCEAO', 'XOF', '952'),
('Bermuda', 'Dólar das Bermudas', 'BMD', '060'),
('Bolívia', 'Boliviano', 'BOB', '068'),
('Bolívia', 'Mvdol', 'BOV', '984'),
('Bonaire, Sint Eustatius e Saba', 'Dólar americano', 'USD', '840'),
('Bósnia e Herzegovina', 'Marco conversível', 'BAM', '977'),
('Botsuana', 'Pula', 'BWP', '072'),
('Brasil', 'Real brasileiro', 'BRL', '986'),
('Brunei Darussalam', 'Dóalres de Brunei', 'BND', '096'),
('Bulgária', 'lev búlgaro', 'BGN', '975'),
('Burkina Faso', 'CFA Franco BCEAO', 'XOF', '952'),
('Burundi', 'Franco do Burundi', 'BIF', '108'),
('Butão', 'Ngultrum', 'BTN', '064'),
('Butão', 'Rupia indiana', 'INR', '356'),
('Bélgica', 'Euro', 'EUR', '978'),
('Cabo Verde', 'Cabo Verde Escudo', 'CVE', '132'),
('Camarões', 'CFA Franc BEAC', 'XAF', '950'),
('Camboja', 'Riel', 'KHR', '116'),
('Canadá', 'Dólar canadense', 'CAD', '124'),
('Cazaquistão', 'Tenge', 'KZT', '398'),
('Chade', 'CFA Franc BEAC', 'XAF', '950'),
('Chile', 'Unidad de Fomento', 'CLF', '990'),
('Chile', 'Peso chileno', 'CLP', '152'),
('China', 'Yuan Renminbi', 'CNY', '156'),
('Chipre', 'Euro', 'EUR', '978'),
('Singapura', 'Dólar de Singapura', 'SGD', '702'),
('Colômbia', 'Peso colombiano', 'COP', '170'),
('Colômbia', 'Unidade de Valor Real', 'COU', '970'),
('Comores', 'Franco Comor', 'KMF', '174'),
( 'Congo', 'CFA Franc BEAC', 'XAF', '950'),
( 'Congo', 'Fran congolesac', 'CDF', '976'),
('Coréia do Sul', 'Won', 'KRW', '410'),
('Coréia do Norte', 'Won norte-coreano', 'KPW', '408'),
('Costa do Marfim', 'CFA Franc BCEAO', 'XOF', '952'),
('Costa Rica', 'Colon da Costa Rica', 'CRC', '188'),
('Croácia', 'Kuna', 'HRK', '191'),
('Cuba', 'Peso conversível', 'CUC', '931'),
('Cuba', 'Peso cubano', 'CUP', '192'),
('Curaçao', 'Guilder das Antilhas Holandesas', 'ANG', '532'),
('Dinamarca', 'Coroa Dinamarquesa', 'DKK', '208'),
('Djibouti', 'Franco do Djibouti', 'DJF', '262'),
('Dominica', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Egito', 'Libra egípcia', 'EGP', '818'),
('El Salvador', 'Cólon de El Salvador', 'SVC', '222'),
('El Salvador', 'Dólar americano', 'USD', '840'),
('Emirados Árabes Unidos', 'UAE Dirham', 'AED', '784'),
('Equador', 'Dólar americano', 'USD', '840'),
('Eritreia', 'Nakfa', 'ERN', '232'),
('Eslováquia', 'Euro', 'EUR', '978'),
('Eslovênia', 'Euro', 'EUR', '978'),
('Espanha', 'Euro', 'EUR', '978'),
('Estados Unidos', 'Dólar americano', 'USD', '840'),
('Estados Unidos', 'Dólar americano (dia seguinte)', 'USN', '997'),
('Estônia', 'Euro', 'EUR', '978'),
('Etiópia', 'Birr etíope', 'ETB', '230'),
('Rússia', 'Rublo', 'RUB', '643'),
('Fiji', 'Dólar de Fiji', 'FJD', 242),
('Filipinas', 'Peso filipino', 'PHP', '608'),
('Finlândia', 'Euro', 'EUR', '978'),
('França', 'Euro', 'EUR', '978'),
('Fundo Monetário Internacional - IMF', 'SDR - Special Drawing Right', 'XDR', '960'),
('Gabão', 'CFA Franc BEAC', 'XAF', '950'),
('Gana', 'Ghana Cedi', 'GHS', '936'),
('Geórgia', 'Lari', 'GEL', '981'),
('Gibraltar', 'Libra de Gibraltar', 'GIP', '292'),
('Granada', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Groelândia', 'Coroa dinamarquesa', 'DKK', '208'),
('Grécia', 'Euro', 'EUR', '978'),
('Guadalupe', 'Euro', 'EUR', '978'),
('Guan', 'Dólar americano', 'USD', '840'),
('Guatemala', 'Quetzal', 'GTQ', '320'),
('Guernsey', 'Libra esterlina', 'GBP', '826'),
('Guiana', 'Dólar da Guiana', 'GYD', '328'),
('Guiana Francesa', 'Euro', 'EUR', '978'),
('Guiné', 'Franco da Guiné', 'GNF', '324'),
('Guiné Equatorial', 'CFA Franc BEAC', 'XAF', '950'),
('Guiné-Bissau', 'CFA Franc BCEAO', 'XOF', '952'),
('Gâmbia', 'Dalasi', 'GMD', '270'),
('Haiti', 'Gourde', 'HTG', '332'),
('Haiti', 'Dólar americano', 'USD', '840'),
('Honduras', 'Lempira', 'HNL', '340'),
('Hong Kong', 'Dólar de Hong Kong', 'HKD', '344'),
('Hungria', 'Forint', 'HUF', '348'),
('Ilha de Bouvet', 'Coroa norueguesa', 'NOK', '578'),
('Ilha de Man', 'Libra esterlina', 'GBP', '826'),
('Ilha do Natal', 'Dólar australiano', 'AUD', '036'),
('Ilha Norfolk', 'Dólar australiano', 'AUD', '036'),
('Ilhas Cayman', 'Dólar das Ilhas Caimã', 'KYD', '136'),
('Ilhas Cocos', 'Dólar australiano', 'AUD', '036'),
('Ilhas Cook', 'Dólar da Nova Zelândia', 'NZD', '554'),
('Ilhas de Aland', 'Euro', 'EUR', '978'),
('Ilhas Falkland - Ilhas Malvinhas', 'Libra das Ilhas Falkland', 'FKP', '238'),
('Ilhas Faroe', 'Coroa dinamarquesa', 'DKK', '208'),
('Ilhas Heard e Ilhas Mcdonald', 'Dólar australiano', 'AUD', '036'),
('Ilhas Marianas do Norte', 'Dólar americano', 'USD', '840'),
('Ilhas MArshall', 'Dólar americano', 'USD', '840'),
('Ilhas Outonares menores dos Estado Unidos', 'Dólar americano', 'USD', '840'),
('Ilhas Salomão', 'Dólar das Ilhas Salomão', 'SBD', '090'),
('Ilhas Virgens - Britânicas', 'Dólar americano', 'USD', '840'),
('Ilhas Virgens (EUA)', 'Dólar americano', 'USD', '840'),
('Indonésia', 'Rupia', 'IDR', '360'),
('Iraque', 'Dinar iraquiano', 'IQD', '368'),
('Irlanda', 'Euro', 'EUR', '978'),
('Irã', 'Rial iraniano', 'IRR', '364'),
('Islândia', 'Coroa da Islândia', 'ISK', '352'),
('Israel', 'Novo Sheqel israelense', 'ILS', '376'),
('Itália', 'Euro', 'EUR', '978'),
('Iêmen', 'Rial Iemenita', 'YER', '886'),
('Jamaica', 'Dólar jamaicano', 'JMD', '388'),
('Japão', 'Iene', 'JPY', '392'),
('Jersey', 'Libra esterlina', 'GBP', '826'),
('Jordânia', 'Dinar jordaniano', 'JOD', '400'),
('Kiribati', 'Dólar australiano', 'AUD', '036'),
('Kuwait', 'Dinar do Kuwait', 'KWD', '414'),
('Laos', 'Kip', 'AK', '418'),
('Lesoto', 'Loti', 'LSL', '426'),
('Lesoto', 'Rand', 'ZAR', '710'),
('Letônia', 'Euro', 'EUR', '978'),
('Libéria', 'Dólar liberiano', 'LRD', '430'),
('Liechtenstein', 'Franco suíço', 'CHF', '756'),
('Lituânia', 'Euro', 'EUR', '978'),
('Luxemburgo', 'Euro', 'EUR', '978'),
('Líbano', 'Libra libanesa', 'LBP', '422'),
('Líbia', 'Dinar da Líbia', 'LYD', '434'),
('Macau', 'Pataca', 'MOP', '446'),
('Macedônia', 'Denar', 'MKD', '807'),
('Madagascar', 'Ariary malgaxe', 'MGA', '969'),
('Malawi', 'Kwacha', 'MWK', '454'),
('Maldivas', 'Rufiyaa', 'MVR', '462'),
('Mali', 'CFA Franc BCEAO', 'XOF', '952'),
('Malta', 'Euro', 'EUR', '978'),
('Malásia', 'Ringgit da Malásia', 'MYR', '458'),
('Mar Santo', 'Euro', 'EUR', '978'),
('Marrocos', 'Dirham marroquino', 'MAD', '504'),
('Martinica', 'Euro', 'EUR', '978'),
('Mauritânia', 'Ouguiya', 'MRO', '478'),
('Maurícia', 'Rupia das Maurícias', 'MUR', '480'),
('Mayotte', 'Euro', 'EUR', '978'),
('Micronésia', 'Dólar americano', 'USD', '840'),
('Moldávia', 'Leão da Moldávia', 'MDL', '498'),
('Mongólia', 'Tugrik', 'MNT', '496'),
('Montenegro', 'Euro', 'EUR', '978'),
('Montserrat', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Moçambique', 'Moçambique Metical', 'MZN', '943'),
('Myanmar', 'Kyat', 'MMK', '104'),
('México', 'Peso mexicano', 'MXN', '484'),
('México', 'Unidade de Investimento Mexicana', '(UDI)', 'MXV', '979'),
('Mónaco', 'Euro', 'EUR', '978'),
('Namíbia', 'Dólares da Namíbia', 'NAD', '516'),
('Namíbia', 'Rand', 'ZAR', '710'),
('Nauru', 'Dólar australiano', 'AUD', '036'),
('Nepal', 'Rupia nepalesa', 'NPR', '524'),
('Nicarágua', 'Cordoba Oro', 'NIO', '558'),
('Nigéria', 'Naira', 'NGN', '566'),
('Niue', 'Dólar da Nova Zelândia', 'NZD', '554'),
('Noruega', 'Coroa norueguesa', 'NOK', '578'),
('Nova Caledônia', 'CFP Franc', 'XPF', '953'),
('Nova Zelândia', 'Dólar da Nova Zelândia', 'NZD', '554'),
('Niger', 'CFA Franc BCEAO', 'XOF', '952'),
('Oman', 'Rial Omani', 'OMR', '512'),
('Palau', 'Dólar americano', 'USD', '840'),
('Palestina', 'Nenhuma moeda universal', '', ''),		
('Panamá', 'Balboa', 'PAB', '590'),
('Panamá', 'Dólar americano', 'USD', '840'),
('Papua Nova Guiné', 'Kina', 'PGK', '598'),
('Paquistão', 'Rupia do Paquistão', 'PKR', '586'),
('Paraguai', 'Guarani', 'PYG', '600'),
('Holanda', 'Euro', 'EUR', '978'),
('Países membros do grupo do banco africado de desenvolvimento', 'Unidade de Conta do ADB', 'XUA', '965'),
('Peru', 'Nuevo Sol', 'PEN', '604'),
('Piticairn', 'Dólar da Nova Zelândia', 'NZD', '554'),
('Polinésia Francesa', 'CFP Franc', 'XPF', '953'),
('Polônia', 'Zloty', 'PLN', '985'),
('Portugal', 'Euro', 'EUR', '978'),
('Porto Rico', 'Dólar americano', 'USD', '840'),
('Qatar', 'Qatari Rial', 'QAR', '634'),
('Quirguistão', 'Som', 'KGS', '417'),
('Quênia', 'Xelim do Quênia', 'KES', '404'),
('Reino Unido', 'Libra esterlina', 'GBP', '826'),
('República Centro-Africana', 'CFA Franc BEAC', 'XAF', '950'),
('República Tcheca', 'Coroa Tcheca', 'CZK', '203'),
('República Dominicana', 'Peso dominicano', 'DOP', '214'),
('Síria', 'Libra síria', 'SYP', '760'),
('Romênia', 'Leu romeno', 'RON', '946'),
('Ruanda', 'Rwanda Franc', 'RWF', '646'),
('Réunion', 'Euro', 'EUR', '978'),
('Saara Ocidental', 'Moroccan Dirham', 'MAD', '504'),
('saint Barthélemy', 'Euro', 'EUR', '978'),
('Saint Helena, Ascension e tristan da Cunha', 'Saint Helena Pound', 'SHP', '654'),
('Saint Kitts e Nevis', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Saint Lucia', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Samoa', 'Tala', 'WST', '882'),
('Samoa Americana', 'Dólar americano', 'USD', '840'),
('San Marino', 'Euro', 'EUR', '978'),
('Senegal', 'CFA Franc BCEAO', 'XOF', '952'),
('Serra Leoa', 'Leone', 'SLL', '694'),
('Seychelles', 'Rúpia das Seychelles', 'SCR', '690'),
('Sint Maarten', 'Guilder das Antilhas Holandesas', 'ANG', '532'),
('SUCRE - Sistema Unitario de Compensacion Regional de Pagos ', 'Sucre', 'XSU', '994'),
('Somália', 'Shilling Somali', 'SOS', '706'),
('Sri Lanka', 'Rupia do Sri Lanka', 'LKR', '144'),
('Suazilândia', 'Lilangeni', 'SZL', '748'),
('Sudão', 'Libra sudanesa', 'SDG', '938'),
('Sudão do Sul', 'Libra Sudanesa do Sul', 'SSP', '728'),
('Suriname', 'Dólar do Suriname', 'SRD', '968'),
('Suécia', 'Swedish Krona', 'SEK', '752'),
('Suíça', 'WIR Euro', 'CHE', '947'),
('Suíça', 'Franco suíço', 'CHF', '756'),
('Suíça', 'WIR Franc', 'CHW', '948'),
('Svalbard e Jan Mayen', 'Coroa norueguesa', 'NOK', '578'),
('São Martinho', 'Euro', 'EUR', '978'),
('São Pierre e Miquelon', 'Euro', 'EUR', '978'),
('São Tomé', 'Dobra', 'STD', '678'),
('São Vicente e grenadines', 'Dólar do Caribe Oriental', 'XCD', '951'),
('Sérvia', 'Dinar sérvio', 'RSD', '941'),
('Tailândia', 'Baht', 'THB', '764'),
('Taiwan', 'Novo dólar de Taiwan', 'TWD', '901'),
('Tajiquistão', 'Somoni', 'TJS', '972'),
('Tanzânia', 'Xelim da Tanzânia', 'TZS', '834'),
('THE - Território Oceano Britânico', 'Dólar americano', 'USD', '840'),
('Territórios do Sul Frânces', 'Euro', 'EUR', '978'),
('Timor-Leste', 'Dólar americano', 'USD', '840'),
('Togo', 'CFA Franc BCEAO', 'XOF', '952'),
('Tokelau', 'Dólar da Nova Zelândia', 'NZD', '554'),
('Tonga', 'Pa’anga', 'TOP', '776'),
('Trinidade e Tobago', 'Dólar de Trinidad e Tobago', 'TTD', '780'),
('Tunísia', 'Dinar tunisino', 'TND', '788'),
('Ilhas Turcas e Caicos', 'Dólar americano', 'USD', '840'),
('Turcomenistão', 'Turcomenistão New Manat', 'TMT', '934'),
('Turquia', 'Lira turca', 'TRY', '949'),
('Tuvalu', 'Dólar australiano', 'AUD', '036'),
('Ucrânia', 'Hryvnia', 'UAH', '980'),
('Uganda', 'Xelim de Uganda', 'UGX', '800'),
('União Euroépia', 'Euro', 'EUR', '978'),
('Uruguai', 'Peso Uruguaio', 'UYU', '858'),
('Uruguai', 'Peso Uruguaio em Unidades Indexadas (URUIURUI)', 'UYI', '940'),
('Uzbequistão', 'Soma do Uzbequistão', 'UZS', '860'),
('Vanuatu', 'Vatu', 'VUV', '548'),
('Venezuela', 'Bolívar', 'VEF', '937'),
('Viet Nam', 'Dong', 'VND', '704'),
('Walliz e Futuna', 'CFP Franc', 'XPF', '953'),
('Zimbábue', 'Dólar zimbabuano', 'ZWL', '932'),
('Zâmbia', 'Zambian Kwacha', 'ZMW', '967'),
('África do Sul', 'Rand', 'ZAR', '710'),
('Áustria', 'Euro', 'EUR', '978'),
('Índia', 'Rupia indiana', 'INR', '356');

/*(((CORREÇÕES FEITAS))) */
